version: '3.7'

services:
  docker-postgres:
    build:
      context: ./docker-postgres
      dockerfile: Dockerfile
    image: docker-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.list
    volumes:
      - ${pwd}./docker-postgres:/home/docker-postgres
      - ${pwd}./data-postgres:/home/data-postgres

  docker-pgadmin4:
    build:
      context: ./docker-pgadmin4
      dockerfile: Dockerfile
    image: docker-pgadmin4
    depends_on:
      - docker-postgres
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env.list
    volumes:
      - ${pwd}./docker-pgadmin4:/var/lib/pgadmin

  docker-python38:
    build:
      context: ./docker-python38
      dockerfile: Dockerfile
    image: docker-python38
    depends_on:
      - docker-postgres
    env_file:
      - .env.list
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ${pwd}./docker-python38:/home/docker-python38
      - ${pwd}./data-python:/home/data-python
