version: '3.7'

services:
  docker-postgres:
    build:
      context: ./docker-postgres
      dockerfile: Dockerfile
    image: docker-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgresdba
      - DB_PASS=postgresdba
      - DB_NAME=db_01
    volumes:
      - ${pwd}/docker-postgres:/home/docker-postgres
      - ${pwd}/data-postgres:/home/data-postgres

  docker-pgadmin4:
    build:
      context: ./docker-pgadmin4
      dockerfile: Dockerfile
    image: docker-pgadmin4
    depends_on:
      - docker-postgres
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ${pwd}/docker-pgadmin4:/var/lib/pgadmin

  docker-python38:
    build:
      context: ./docker-python38
      dockerfile: Dockerfile
    image: docker-python38
    depends_on:
      - docker-postgres
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ${pwd}/docker-python38:/docker-python38
      - ${pwd}/data-python:/data-python
